# GitHub Sponsors funding file
# Uncomment and add your details if you want to accept sponsorships

# github: [yourusername]
# patreon: yourusername
# open_collective: yourproject
# ko_fi: yourusername
# custom: ['https://www.buymeacoffee.com/yourusername']
